### ISSUE TITLE
Idea

### ISSUE THREAD

**Issue by chrisblossom** [nzakas/eslint-plugin-typescript#1]
Just a thought, would it be more efficient to fork [gajus/eslint-plugin-flowtype](https://github.com/gajus/eslint-plugin-flowtype) and tweak for Typescript from there? I would think a lot of rules would work both ways.

**Comment by nzakas** [comment]
It could be, I just don't have the energy to do that at the moment. If you're interested, in seeing what could work for TypeScript, I'd happily review some PRs.

**Comment by JamesHenry** [comment]
Closing as this does not have any action item associated with it. As Nicholas says, any contributions are more than welcome :)
