### ISSUE TITLE
Unnet peer dependency typescript@1.7.3

### ISSUE THREAD

**Issue by PinkFLoyd92** [nzakas/eslint-plugin-typescript#11]
I cannot install the plugin, it asks the for a lower version of my actual typescript version. plz help :(
![typescript](https://cloud.githubusercontent.com/assets/8844096/19777190/b1e6f394-9c3c-11e6-9100-792bbd562bf7.jpg)

**Comment by nzakas** [comment]
I'm sorry, you can't use the plugin with TypeScript 2.0 yet. The TypeScript ESLint parser hasn't yet been updated for TypeScript 2.0. Until then, you won't be able to use ESLint with TypeScript 2.0.
