### ISSUE TITLE
Manually mark TypeScript-specific nodes as used

### ISSUE THREAD

**Issue by JamesHenry** [nzakas/eslint-plugin-typescript#2]
From @nzakas:

> In the short-term, we can probably add a rule in eslint-plugin-typescript that manually marks the identifier as used. eslint-plugin-react had to do something similar for some JSX stuff: https://github.com/yannickcr/eslint-plugin-react/blob/master/lib/rules/jsx-uses-vars.js

Example of decorators can be seen here: https://github.com/eslint/typescript-eslint-parser/issues/55

**Comment by JamesHenry** [comment]
This will now be split into two parts:

- [ ] a new rule in this plugin to manually mark certain things as used
- [ ] extending a new ESLint fork of escope to traverse into typeAnnotations

**Comment by nzakas** [comment]
@JamesHenry the second part is what will be handled in ESLint directly, not in escope (or a fork).

**Comment by JamesHenry** [comment]
@nzakas Ah sorry, I think I misunderstood this description https://github.com/eslint/eslint/issues/7129

**Comment by mightyiam** [comment]
Fixed?

**Comment by JamesHenry** [comment]
This issue was very out of date and therefore a misleading reference for people.

The recommended way to enforce "no unused" behaviour is still to use the typescript compiler itself. noUnusedParameters and noUnusedLocals are the relevant options.

If you experiencing specific problems with the plugin then please create new issue(s) for them.
