### ISSUE TITLE
type-annotation-spacing rule doesn't work for class properties

### ISSUE THREAD

**Issue by unlight** [nzakas/eslint-plugin-typescript#24]
```
export class HelloComponent {
    title : string = 'Hello :)';
}
```

**Comment by soda0289** [comment]
It also needs to check parameter properties in constructors as well.

**Comment by weirdpattern** [comment]
Submitted a new PR to fix this issue.
Extended the rule by adding options to control the spacing before and after the colon, so now the rule supports more than one spacing pattern (spaces before and after; spaces before, but not after; etc).
