### ISSUE TITLE
Rules missing in current NPM release

### ISSUE THREAD

**Issue by luchsamapparat** [nzakas/eslint-plugin-typescript#25]
Is there a timeline when we can expect the rules documented in the README.md to be released via NPM? Currently, when I install via NPM I only get explicit-member-accessibility and type-annotation-spacing.

**Comment by soda0289** [comment]
@JamesHenry Could we get a release

**Comment by JamesHenry** [comment]
I do not have access to that, and I'm not sure how @nzakas has been handling the releases given it is under his personal account. I will follow up with him.

Until then, npm installing from github should work for you @luchsamapparat

**Comment by soda0289** [comment]
@JamesHenry Sorry to bother you then, will wait for @nzakas.

**Comment by weirdpattern** [comment]
I think it will be a good idea to update the typescript parser version before we release.
Also, there are a couple of rules that still need approval :)

**Comment by flying-sheep** [comment]
hi, any news? i’d like to see the `no-unused-vars` thing in a release

**Comment by mattdell** [comment]
Same here. I'd like to use `no-unused-vars` but work only allows us to proxy to npmjs.org.

Need a release!

**Comment by kayneb** [comment]
Likewise!!! Wanting to use `no-unused-vars` too.

**Comment by soda0289** [comment]
Will try and get a new release this week. The ESLint team is working on creating an automated process for future releases.

**Comment by soda0289** [comment]
Unfortunately it is not possible for the ESLint team to push a release to npm. @nzakas is currently taking a break from this project for health reasons and there might be a further delay until another release. 

In the mean time work can still continue work here and maybe create a fork that we can push to npmjs or release a tarball of the current master branch.

**Comment by corbinu** [comment]
@soda0289 I am happy to do maintain a release fork @corbinu/eslint-plugin-typescript until nzakas is feeling better if that is cool with you all?

**Comment by soda0289** [comment]
That would be fine with me.

@JamesHenry Would this be an acceptable solution, should we update the README here to indicate the current situation?

**Comment by corbinu** [comment]
published as version 0.2.0

**Comment by corbinu** [comment]
@soda0289 whats your npm username is it the same? I will add you with publish rights also.

**Comment by JamesHenry** [comment]
We got all the permissions straightened out, I have just published `eslint-plugin-typescript@0.3.0`
