### ISSUE TITLE
no-explicit-any Rule does not check generic type

### ISSUE THREAD

**Issue by soda0289** [nzakas/eslint-plugin-typescript#26]
For example:

```ts
function test(): Promise<any> {
return new Promise();
}
```

Maybe we can include an extra option?

**Comment by soda0289** [comment]
It also never checks class properties or constructor parameter properties.

**Comment by weirdpattern** [comment]
Submitted a new PR to fix this issue.
I added a couple of extra scenarios (see PR) that were not included/mentioned in this bug.
