### ISSUE TITLE
Some illegitimate failures?

### ISSUE THREAD

**Issue by mightyiam** [nzakas/eslint-plugin-typescript#27]
Travis run of [this pull request](https://github.com/mightyiam/cyclejs-web-components/pull/13) has some seemingly illegitimate failures.

**Comment by soda0289** [comment]
You will have to post a code sample to reproduce the error and output from eslint. How do you know there is an issue with the plugin and not the parser?

Check my comment here for what I think the issue could be: https://github.com/eslint/typescript-eslint-parser/issues/179

**Comment by JamesHenry** [comment]
I am going to close this as no further information was provided
