### ISSUE TITLE
Consider babel-eslint for parser?

### ISSUE THREAD

**Issue by jquense** [nzakas/eslint-plugin-typescript#285]
👋 Heyo, thanks for taking the time maintaining this. It's great to have a tslint alternative. I was wondering if you'd looked taking advantage of babel's new ability to parse typescript. It might be a win to not have to maintain a separate ts to estree parser if babel-eslint gives you that for free.

**Comment by armano2** [comment]
@jquense babel typescript has a lot of issues with ast, i was patching some of them, but ast ranges are kinda broken for now..

`typescript-estree` is ~aligned with babel but there is no visitor-keys and scope analysis from babel yet for typescript.

some of latests issues:
- https://github.com/babel/babel/issues/9319
- https://github.com/babel/babel/issues/9305
- https://github.com/babel/babel/issues/9304
and so on....

prs not yet released:
- https://github.com/babel/babel/pull/9302
- https://github.com/babel/babel/pull/9295
- https://github.com/babel/babel/pull/9292
- https://github.com/babel/babel/pull/9276
- https://github.com/babel/babel/pull/9230
there is more waiting in queue

in [typescript-estree](https://github.com/JamesHenry/typescript-estree) we are running alignment tests from babel, and for now they are not ready yet...

**Comment by bradzacher** [comment]
Short answer: no, we won't switch to babel-eslint.

There's a slim chance we might support it as well, if they give us the same quality AST that we get from typescript-eslint-parser.
Though right now TBH my stance is that there's little point in increasing the maintenance cost to support two parsers with different implementations.


Long answer:
In the beginning, the parser existed solely to support the TS nodes.

In the very near future, this will change. The parser will expose the parser services directly from typescript. This will give us direct access to in-depth type information about everything, enabling us to develop powerful rules (we'll be to add a number of rules that exist in tslint).

For examples, see the [currently open `WIP` PRs](https://github.com/bradzacher/eslint-plugin-typescript/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3AWIP).

**Comment by armano2** [comment]
@bradzacher this plugin is going to support both of them, ast structure is almost identical, and after next ts-eslint-parser it will be almost equal...

our goal is to produce unified ast structure than if someone is going to want to use different parser he will be able to (without rules with type checking)
