### ISSUE TITLE
Adding a pre-commit hook to execute lint and tests

### ISSUE THREAD

**Issue by weirdpattern** [nzakas/eslint-plugin-typescript#51]
I think we all could benefit from having a pre-commit hook to make sure everything is in order before committing our code. If everybody is ok with this, I would like to add [pre-commit](https://www.npmjs.com/package/pre-commit) to the project...

Of course I'm open to suggestions in case anyone has a better idea 😄

**Comment by j-f1** [comment]
You might also want to take a look at [`husky`](https://www.npmjs.com/package/husky), too.

**Comment by weirdpattern** [comment]
Even better, thanks for letting me know @j-f1 
I will do this tonight
