### ISSUE TITLE
member-delimiter-style single-line override

### ISSUE THREAD

**Issue by nevir** [nzakas/eslint-plugin-typescript#58]
Today, with `member-delimiter-style: error`:

```ts
export interface Foo { [key: string]: any }
//                                    ^ Expected a semicolon.
```

Suggestion: add an override/option to disable this check for single line type signatures

**Comment by weirdpattern** [comment]
You can use `requireLast` to ignore these...

**Comment by weirdpattern** [comment]
But yeah, I see the benefits of having a separate option for this.
I will work on this

**Comment by nevir** [comment]
> You can use requireLast to ignore these...

Well, but ideally it'd be required when the list is expanded
