### ISSUE TITLE
Breaking changes to some TSNode types coming in typescript-eslint-parser

### ISSUE THREAD

**Issue by JamesHenry** [nzakas/eslint-plugin-typescript#74]
PR: https://github.com/eslint/typescript-eslint-parser/pull/388
Issue: https://github.com/eslint/typescript-eslint-parser/issues/386
Background: https://github.com/babel/babylon/pull/710

Should be very straightforward to track down any occurrences of the affected nodes and prefix them with `TS`

**Comment by weirdpattern** [comment]
What's the timeline for this @JamesHenry?
I can work on this, but can't do it before the weekend, can we wait until then?

**Comment by JamesHenry** [comment]
There shouldn't be any real pressure to update the parser in this codebase, it's not blocking any features/fixes etc

So even if the parser PR gets merged over the next few days, the plugin update can definitely wait a bit longer, just wanted to open the issue to give visibility

**Comment by weirdpattern** [comment]
Understood, then I will work on this over the weekend, as you said this should be an easy fix...

**Comment by weirdpattern** [comment]
Initial work in [weirdpattern/support-updated-ts-nodes](https://github.com/weirdpattern/eslint-plugin-typescript/tree/support-updated-ts-nodes).

To test:

```bash
$ npm install eslint/typescript-eslint-parser#fbb98c416806a034bcccad765ed5a67ac880213f
$ npm run test
```

I will update the parser package dependency (and any other) once work on [PR 388](https://github.com/eslint/typescript-eslint-parser/pull/388) has been completed and a new release of the parser has been published to npm.

**Comment by weirdpattern** [comment]
@JamesHenry where are we on this? 
I see some of the issues/PRs have already been merged.

**Comment by JamesHenry** [comment]
Thanks for your patience on this @weirdpattern! I have submitted a PR to prettier confirming the relevant changes there too, so we are basically good to go on this now I think.

Any problems getting the plugin updated?

**Comment by weirdpattern** [comment]
No, shouldn't be a problem.
I will do it in the next couple of days, if not today....

**Comment by JamesHenry** [comment]
Ok no problem, it will be a major version bump in the parser anyway so there shouldn't be any timing issues

**Comment by weirdpattern** [comment]
If that is the case, shouldn't I wait until the parser has been updated so I can update the version in our package.json file?

**Comment by j-f1** [comment]
@weirdpattern You can just use a commit from GitHub to get the PR started, then switch to the npm version once the parser changes get released.

**Comment by weirdpattern** [comment]
@j-f1 yeah that's how I did it when I implemented the changes. I was just hoping to avoid a second (or third) rebase/commit to my code... no biggie... I will keep doing what I did before (point to the commit) then update the version...

**Comment by JamesHenry** [comment]
It's merged and I've released v10.0.0

**Comment by weirdpattern** [comment]
Perfect, I will take it from here

**Comment by weirdpattern** [comment]
Alrigth, it's done 😄
