### ISSUE TITLE
Some space-infix-ops bug

### ISSUE THREAD

**Issue by mightyiam** [nzakas/eslint-plugin-typescript#85]
Sorry for submitting it like this, with a screenshot from the IDE. I tried creating a PR with a failing test case. That escalated quickly.

![screenshot_2017-10-09_22-19-39](https://user-images.githubusercontent.com/635591/31354758-370de856-ad40-11e7-919a-8d2d8d09a3e0.png)

**Comment by mightyiam** [comment]
Is this fixed by now, maybe?

**Comment by macklinu** [comment]
[`space-infix-ops`](https://eslint.org/docs/rules/space-infix-ops) is present in the ESLint core, not this plugin. I'm not sure what the proper next step is, but I would guess that this issue should be opened in the ESLint repo. The only slightly related issue I could find to this (type annotations + space-infix-ops) is https://github.com/eslint/eslint/issues/5211.

**Comment by macklinu** [comment]
I'm thinking, based on https://github.com/nzakas/eslint-plugin-typescript/issues/101#issuecomment-372155440, that we'd need to fork the `space-infix-ops` rule into this plugin and handle this test case.

**Comment by zuzusik** [comment]
There is also issue in parser for this: https://github.com/eslint/typescript-eslint-parser/issues/486

**Comment by madbence** [comment]
I opened eslint/eslint#10922 and eslint/eslint#10923 that can possibly resolve false positives, but it means that a new rule has to be added to `eslint-plugin-typescript`. as an alternative,  [`typescript-estree`](https://github.com/JamesHenry/typescript-estree) could parse type aliases differently, see JamesHenry/typescript-estree#17.

**Comment by madbence** [comment]
eslint/eslint#10935 fixed this i think (`eslint@5.7.0`), can you confirm @mightyiam ?

**Comment by mightyiam** [comment]
Confirmed with `eslint@5.8.0`.

**Comment by mightyiam** [comment]
Thank you, @madbence.
